#!/bin/sh

set -e

TESTDIR=$(pwd)/debian/tests/ciphertest

if [ "$1" = "--qt6" ]; then
  CONF_FLAGS="-DQT_VERSION=6"
elif [ "$1" = "--qt5" ]; then
  CONF_FLAGS="-DQT_VERSION=5"
else
  echo "Usage $1 --qt5|--qt6"
  exit 1
fi

cd "$AUTOPKGTEST_TMP"

echo Building test
cmake $CONF_FLAGS "$TESTDIR"
make
echo OK

echo Running test
./ciphertest
echo OK
